# Generated by Django 5.1.5 on 2025-01-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baner',
            name='baner',
        ),
        migrations.AddField(
            model_name='baner',
            name='img',
            field=models.ImageField(default=1, upload_to='baners/'),
            preserve_default=False,
        ),
    ]
