# Generated by Django 5.1.5 on 2025-01-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_baner_baner_baner_img'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together={('product', 'color', 'size')},
        ),
    ]
